apiVersion: v1
kind: Service
metadata:
  name: registry-headless
  labels:
    app: registry
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8761
  selector:
    app: registry

---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  type: NodePort
  ports:
  - name: http
    port: 8761
    nodePort: 30001
  selector:
    app: registry

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
spec:
  serviceName: registry-headless
  replicas: 2
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: jacarrichan/cloud-registry:1.2.0
        env:
        - name: PORT
          value: "8761"
        - name: REGISTRY_SERVICE_URL
          value: "http://registry-0.registry-headless.default.svc.cluster.local:8761/eureka,http://registry-1.registry-headless.default.svc.cluster.local:8761/eureka"
        - name: REGISTRY_SERVICE_HA
          value: "true"
        ports:
        - name: http
          containerPort: 8761

