apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: jacarrichan/cloud-service-b:1.2.0
        env:
        - name: PORT
          value: "8080"
        - name: REGISTRY_SERVICE_URL
          value: "http://registry-0.registry-headless.default.svc.cluster.local:8761/eureka,http://registry-1.registry-headless.default.svc.cluster.local:8761/eureka"
        ports:
        - name: http
          containerPort: 8080

