apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: jacarrichan/cloud-service-b:1.2.0
          env:
            - name: PORT
              value: "8080"
            - name: REGISTRY_SERVICE_URL
              value: "http://registry-0.registry-headless.default.svc.cluster.local:8761/eureka,http://registry-1.registry-headless.default.svc.cluster.local:8761/eureka"
            - name: ZIPKIN_SERVICE_URL
              value: "http://zipkin-server:9422"
            # kubernetes为每个容器配置默认是${namespace}.svc.cluster.local
            - name: LOG_KAKFA_SERVICE_URL
              value: "http://kafka-0.kafka-svc.default.svc.cluster.local:9092"
          ports:
            - name: http
              containerPort: 8080

