apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: jacarrichan/cloud-service-a:1.2.0
        env:
        - name: PORT
          value: "8080"
        - name: REGISTRY_SERVICE_URL
          value: "http://registry-0.registry-headless.default.svc.cluster.local:8761/eureka,http://registry-1.registry-headless.default.svc.cluster.local:8761/eureka"
        - name: ZIPKIN_SERVICE_URL
          value: "http://zipkin-server:9422"
        ports:
        - name: http
          containerPort: 8080

