---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-server
  labels:
    app: zipkin-server
spec:
  type: NodePort
  ports:
    - name: http
      port: 9422
      nodePort: 32311
  selector:
    app: zipkin-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-server
  template:
    metadata:
      labels:
        app: zipkin-server
    spec:
      containers:
      - name: zipkin-server
        image: jacarrichan/cloud-zipkin-server:1.2.0
        env:
        - name: PORT
          value: "9422"
        - name: REGISTRY_SERVICE_URL
          value: "http://registry-0.registry-headless.default.svc.cluster.local:8761/eureka,http://registry-1.registry-headless.default.svc.cluster.local:8761/eureka"
        ports:
        - name: http
          containerPort: 9422

